Youtube api test
b02902092/Youtube-Reminder pull request #2
Opened 2020-04-21 05:12 UTC by b02902092

Youtube APIを叩いて、生のJsonファイルがもらった。

2020-04-22 02:34 UTC, b02902092 commented
@saitoyu 修正は完成しました。確認をお願いします！

2020-04-23 03:56 UTC, saitoyu commented
2327484f6adc112811542c78130e25e115a60547 のコミットってなんですか？？ commit comment 見る限り master の最新を取り込みたかったのかと思うのですが、その場合は merge じゃなくて rebase してください。

2020-04-23 04:05 UTC, saitoyu commented
レビュワーはコミット単位で修正内容を追っていくので、時系列がわかりやすいようなコミットの積み方をするのは意識してやってみて欲しいです。大きいタスクをこなすときなど修正箇所が大きいときほどコミットの仕方とかコミットコメントの付け方には気を配って欲しいです。

2020-04-23 04:44 UTC, saitoyu requested changes
@b02902092 コメントしました。

2020-04-23 04:44 UTC, saitoyu commented on src/main/java/com/example/demo/DemoApplication.java
> +        String param = "?part=id" +
結果 `java.net.URL` に変換されるなら、`YoutubeApiClient#getVideo` の引数は `java.net.URL`  で受ければ良いと思います。
Java は型安全な言語だと思うので、そのメリットを生かしてインターフェースも正しい型で定義するよう意識しましょう。

2020-04-23 04:44 UTC, saitoyu commented on src/main/java/com/example/demo/YoutubeApiClient.java
> +    public String getVideo (String param, String path) {
これ youtube api の url を見るに複数件返ってくると思うので getVideo's' ですよね

2020-04-23 04:44 UTC, saitoyu commented on src/main/java/com/example/demo/YoutubeApiClient.java
> +    public String getVideo (String param, String path) {
これはあとで繋ぎこみするときでもいいんですが、Jackson 使ってレスポンス情報は POJO で扱うようにできると良いかと思います。

2020-04-23 04:44 UTC, saitoyu commented on src/main/java/com/example/demo/DemoApplication.java
> +        String json = y.getVideo(param, youtubeApiUrl);
`y.` ってなんだっけってなるので変数名はちゃんとつけましょう。今は小さいアプリケーションなので気にならないかもしれませんが。
これは個人的な意見ですけど、短くて何かわからないよりは、冗長だけど意味がわかる方が良いと思ってます。（本当は短くて意味がわかるが一番良いんですけど難しい、

2020-04-23 04:44 UTC, saitoyu commented on src/main/java/com/example/demo/YoutubeApiClient.java
> +    public String getVideo (String param, String path) {
あと今の作りだと static メソッドでも良いきがするんですが、何か考えがあってインスタンスメソッドにしてますか？？

2020-04-23 05:06 UTC, merged