slack api can work
b02902092/Youtube-Reminder pull request #3
Opened 2020-04-21 08:21 UTC by b02902092

2020-04-21 08:52 UTC, saitoyu commented
@b02902092 

まず、コードレビューの前にPRについてコメントします。
ブランチ名変更するのは手間なので対応しなくて良いんですが、他は直してみてください

- 作業ブランチは `feature/` プレフィックスをつけましょう
  - 今回の場合だったら、 `feature/git_test` です
  - もっと言うとブランチの名前もちゃんとPRの内容にそった名前にしましょう
- description はできるだけ詳細に書きましょう
  - どういう目的でどんな対応をしたのか、このPRを初めてみる人でもわかるように書きましょう
    - もちろんレビュワーに内容を伝える目的もありますが、あとでPRを振り返って参照したときのログ的な意味合いもあります。

- PR でレビューを依頼するときはマージできる状態でレビュー依頼をしましょう。
  - 今回の場合、conflicts を解消してから依頼しましょう

2020-04-22 02:34 UTC, b02902092 commented
@saitoyu 修正は完成しました。確認をお願いします！

2020-04-22 02:38 UTC, saitoyu commented
@b02902092 ありがとうございます！コードレビューもしていきます

2020-04-22 03:53 UTC, saitoyu requested changes
とりあえず修正して欲しいなと思うところはコメントしてみました。

あと test って別のPRで対応しますか？？後でも良いんですが test は書いて欲しいです。

2020-04-22 03:53 UTC, saitoyu commented on src/main/java/com/example/demo/SlackPostJson.java
> +public class SlackPostJson {
クラス名はそのクラスの責務がわかるような名詞を用いてつけましょう。
参考）https://qiita.com/KeithYokoma/items/ee21fec6a3ebb5d1e9a8

例えばこのクラスってslack 用のAPIクライアントだと思うので、`SlackApiClient` で良いのかなと思います
（もっというと Slack API を叩くかどうかはパラメータとして受けていているので `ApiClient` ぐらいの汎用的な名前にもなり得そうだと思いました）

2020-04-22 03:53 UTC, saitoyu commented on src/main/java/com/example/demo/SlackPostJson.java
> +    public String slackPostJson(String json, String path) {
メソッド名も動詞を用いてつけましょう（名詞はクラス名になるので不要です）
参考） https://qiita.com/KeithYokoma/items/2193cf79ba76563e3db6

上を直すとこのメソッドを呼ぶときに `new SlackApiClient().postJson("hoge","fuga")`  となるのでわかりやすいです。

2020-04-22 03:53 UTC, saitoyu commented on src/main/java/com/example/demo/SlackPostJson.java
> +    public String slackPostJson(String json, String path) {
もう少し言うとこの場合って slack api を叩くための方法（json を post する）をメソッド名にするのではなくて、Slackに対してどう言う操作をするのかをメソッド名にするべきだと思います。

例えば、「Slack にメッセージを投稿する」がこのメソッドの役割だと思うので、`postMessage` とか。
「Slack にメッセージを投稿する」ためにどういった処理をしてるかは この api を利用する側は気にする必要がないので

2020-04-22 03:53 UTC, saitoyu commented on src/main/java/com/example/demo/DemoApplication.java
>                  "\"as_user\"=\"1\"" +
クレデンシャル情報を生であげるのは絶対にやめましょう（多分生だと思うのですが
ましてや public リポジトリなので、、

https://github.com/b02902092/Youtube-Reminder/pull/3/files#diff-e96e670169a8443d1ccdfa499d86cd6fR18

2020-04-22 03:53 UTC, saitoyu commented on src/main/java/com/example/demo/SlackPostJson.java
> +            return "client - IOException : " + e.getMessage();
非検査例外で特に例外が発生したときに特別なアクションが必要ないなら、非検査例外にラップして投げましょう。今回だと `IOException` ラップした `UncheckedIOException` という非検査例外があるのでそれを使いましょう

私も`UncheckedIOException` と言う存在を最近知ったんですが、、

2020-04-22 03:53 UTC, saitoyu commented on src/main/java/com/example/demo/DemoApplication.java
> +        System.out.println(p.slackPostJson(json, path));
実際は定期（毎日）に動くこと想定してると思ってますが、今回は client の動作確認のために main メソッドに書いているという理解であってますか？？

2020-04-22 03:53 UTC, saitoyu commented on src/main/java/com/example/demo/SlackPostJson.java
> +        try {
stream 扱うときは finally で明示的にクローズするか、try-with-resources 句を使ってください。でないと途中で例外なりが発生したときにそのリソースが閉じられないので
https://docs.oracle.com/javase/jp/7/technotes/guides/language/try-with-resources.html

2020-04-22 04:02 UTC, saitoyu commented
あと、Java で Json を扱うときは Jackson というライブラリが使われることが多いです。
私たちのチームのプロダクトでも利用しているのでこれを使ってもらうと良いかもしれません。
https://itsakura.com/java-jackson#s1

2020-04-22 04:02 UTC, saitoyu commented
@b02902092 レビューしました

2020-04-22 06:06 UTC, b02902092 commented on src/main/java/com/example/demo/DemoApplication.java
> +        System.out.println(p.slackPostJson(json, path));
はい、そうです！

2020-04-22 07:51 UTC, saitoyu commented on src/main/java/com/example/demo/SlackPostJson.java
> +            return "client - IOException : " + e.getMessage();
非検査例外について https://itsakura.com/java-hikensa-reigai

2020-04-22 08:41 UTC, b02902092 commented
@saitoyu 直してみました。ご確認ください！

2020-04-22 08:52 UTC, saitoyu approved these changes
コメントしましたが、lgtm

2020-04-22 08:52 UTC, saitoyu commented on src/main/java/com/example/demo/SlackApiClient.java
> +        try (OutputStreamWriter out = new OutputStreamWriter(
try-with-resource って確か複数リソース指定できたはずなのでリソースごとに書かないで一つにまとめられると思います

```
try(OutputStreamWriter out = new OutputStreamWriter(new BufferedOutputStream(uc.getOutputStream())),
BufferedReader in = new BufferedReader(new InputStreamReader(uc.getInputStream()))
) {

} catch (IOException e) {
            throw new UncheckedIOException(e);
        }

```

2020-04-22 08:54 UTC, saitoyu commented
@b02902092 次回からで構わないのですが、修正コミットはまとめないで指摘された単位でコミットしてください。そうするとレビュワーは指摘に対する修正内容を追いやすくなるので

2020-04-22 09:13 UTC, b02902092 commented
> @b02902092 次回からで構わないのですが、修正コミットはまとめないで指摘された単位でコミットしてください。そうするとレビュワーは指摘に対する修正内容を追いやすくなるので

はい、すみません。次回から一つの問題に対してcommitします。

2020-04-22 09:15 UTC, b02902092 commented on src/main/java/com/example/demo/SlackApiClient.java
> +        try (OutputStreamWriter out = new OutputStreamWriter(
> try-with-resource って確か複数リソース指定できたはずなのでリソースごとに書かないで一つにまとめられると思います
> 
> ```
> try(OutputStreamWriter out = new OutputStreamWriter(new BufferedOutputStream(uc.getOutputStream())),
> BufferedReader in = new BufferedReader(new InputStreamReader(uc.getInputStream()))
> ) {
> 
> } catch (IOException e) {
>             throw new UncheckedIOException(e);
>         }
> ```

勉強になりました。修正します！

2020-04-22 09:22 UTC, b02902092 commented on src/main/java/com/example/demo/SlackApiClient.java
> +        try (OutputStreamWriter out = new OutputStreamWriter(
試してみました。でも一緒に書くことはできないみたいです。もしwriteがしないならInputStreamReaderは作れないと思います。
先の実験は400 bad requestをもらいました。

2020-04-22 09:30 UTC, merged