 Youtube APIを叩く機能について修正しました
b02902092/Youtube-Reminder pull request #4
Opened 2020-04-23 06:38 UTC by b02902092

1. getVideo()はgetVideios()に修正しました。複数の動画がもらえるから。
2. getVideo()はstaticの方がいいと思いますからそれを直しました。最初は深く考えてないからstaticを付けませんでした。
3. 変数yはyoutubeApiClientに修正しました。他人には理解できる名前に変更しました。
4. getVideoのparameterはjava.net.URLに修正しました。

これからやること：jacksonを導入すること

2020-04-24 09:43 UTC, saitoyu requested changes
コメントしましたー

2020-04-24 09:43 UTC, saitoyu commented on src/main/java/com/example/demo/YoutubeApiClient.java
> +    public static String getVideos (URL url) {
意地悪い質問の仕方なんですがなぜ static が正しいと思いました？？ （static が間違えてると言いたい訳ではないです）
元の質問の意図はクラスメソッドとインスタンスメソッドの使い分けを意識してやってるのか確認したかったので今回 static を採用した理由を聞きたいです。

2020-04-24 09:43 UTC, saitoyu commented on src/main/java/com/example/demo/DemoApplication.java
>          String youtubeApiUrl = "https://www.googleapis.com/youtube/v3/videos";
オブジェクト志向な実装をする上でもう少しクラスの責務を意識するといいと思います。
例えば getVideos といいつつ実際の url を利用する側が設定するのは違和感があります。どの url をどう叩くかはこのクライアントの責務のはずなので。
（正しく動作するかとう観点でも getVideo に videos じゃない url を指定したら意図した動作にならないと思います

もう少し言うと、`YoutubeApiClient` が youtube 専用のクラスだとしたら url ってパラメータとして渡す必要ないと思います。どの api を利用するにしても変わるのってパスだけですよね。

2020-04-24 09:43 UTC, saitoyu commented on src/main/java/com/example/demo/DemoApplication.java
>          String youtubeApiUrl = "https://www.googleapis.com/youtube/v3/videos";
じゃあどう直すといいのかは一度考えてみてもらえると 🙏

2020-04-24 09:43 UTC, saitoyu commented on src/main/java/com/example/demo/YoutubeApiClient.java
> +    public static String getVideos (URL url) {
仮に static にするとしたら、↓でインスタンス生成する意味はないですよね
https://github.com/b02902092/Youtube-Reminder/pull/4/files#diff-e96e670169a8443d1ccdfa499d86cd6fR14

2020-04-24 09:43 UTC, saitoyu commented on src/main/java/com/example/demo/DemoApplication.java
> +            throw new RuntimeException(); //ここは何を投げればいいですか？
> //ここは何を投げればいいですか？

今回の場合みたいな時はコードコメントではなくて github のインラインコメント利用するといいと思います。
なぜなら、仮にこれで問題ない場合でもこのコメントを消す手間（コミット）が発生すると思うので。

2020-04-24 09:43 UTC, saitoyu commented on src/main/java/com/example/demo/DemoApplication.java
> +            throw new RuntimeException(); //ここは何を投げればいいですか？
ちなみにこれって質問ってことであってますよね？？
だとするとライくんは何が問題だと思っているのかまず確認したいです

2020-04-24 09:58 UTC, saitoyu commented on src/main/java/com/example/demo/DemoApplication.java
>          String youtubeApiUrl = "https://www.googleapis.com/youtube/v3/videos";
ちょっと考えみて :wakaran: って感じだったら一緒に考えましょう

2020-04-27 09:15 UTC, b02902092 commented on src/main/java/com/example/demo/YoutubeApiClient.java
> +    public static String getVideos (URL url) {
> 意地悪い質問の仕方なんですがなぜ static が正しいと思いました？？ （static が間違えてると言いたい訳ではないです）
> 元の質問の意図はクラスメソッドとインスタンスメソッドの使い分けを意識してやってるのか確認したかったので今回 static を採用した理由を聞きたいです。

今の機能がユーティリティメソッドだと思いますのでstaticの方が使ったらインスタンスを作る必要がないから可読性も上げると思います。
以前作ったインスタンスの消しは忘れてしまいましたからそれを直します。

2020-04-28 09:43 UTC, b02902092 commented on src/main/java/com/example/demo/YoutubeApiClient.java
> +    public static String getVideos (URL url) {
この問題の修正は完成しました。ご確認ください！

2020-04-28 09:47 UTC, saitoyu commented on src/main/java/com/example/demo/YoutubeApiClient.java
> +    public static String getVideos (URL url) {
azms

2020-04-28 09:48 UTC, saitoyu commented on src/main/java/com/example/demo/DemoApplication.java
> +            throw new RuntimeException(); //ここは何を投げればいいですか？
これも #5 で直してもらった

2020-04-28 09:58 UTC, b02902092 commented
タスクを修正しました。
1. YoutubeのAPI urlは今YoutubeApiClientに記載しています。そして定数化しました。
2. 無用なライブラリーを消しました。

2020-04-28 10:56 UTC, saitoyu approved these changes
コメントしましたー
あとで対応してらうでもいいです

https://github.com/b02902092/Youtube-Reminder/pull/4#discussion_r414366340 にも書いたんですが、どこまでがこのクラスの責務なのか意識するといいと思います。

2020-04-28 10:56 UTC, saitoyu commented on src/main/java/com/example/demo/YoutubeApiClient.java
> +    public static String getVideos (String param) {
パラメータも必要なだけをうけるようにするといいと思いました。
今実質指定できるのって key と maxResults だけだと思うので↓でいいのでは無いかなと
getVideo 時のパスパラメータをどう組み立てるか利用者側が意識する必要は無いので

```
public static String getVideos (String key, int maxResults) {
```

2020-04-28 10:56 UTC, saitoyu commented on src/main/java/com/example/demo/YoutubeApiClient.java
> +        final String youtubeApiUrl = "https://www.googleapis.com/youtube/v3/videos";
`https://www.googleapis.com/youtube/v3/` ってこの api クラスで共通のurlだと思っていて、であるならクラス変数にしてもいいのかなと思いました。

2020-04-28 10:56 UTC, saitoyu commented on src/main/java/com/example/demo/DemoApplication.java
> +            json = YoutubeApiClient.getVideos(param);
利用者側で String で扱う需要が無いなら、このメソッドの戻りも `YoutubeApiJson` にしてしまっていいと思います。

2020-04-28 10:57 UTC, merged

2020-04-28 10:58 UTC, b02902092 commented on src/main/java/com/example/demo/YoutubeApiClient.java
> +        final String youtubeApiUrl = "https://www.googleapis.com/youtube/v3/videos";
そうですね。クラス変数にします！